### ISSUE TITLE
MacOS Mojave Xcode error

### ISSUE THREAD

**Issue by Dev1352** [coolstar/electra1131#13]
/Users/dev135/Library/Developer/Xcode/DerivedData/electra1131-bmisvxehyriprbfuwdinqmbpzqit/Build/Intermediates.noindex/electra1131.build/Debug-iphoneos/electra1131.build/DerivedSources/basebinaries.tar: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by akasarx** [comment]
it literally tells you what's wrong.

**Comment by tylinux** [comment]
Make sure your ldid, ldid2 and gnu-tar is installed.
