### ISSUE TITLE
iPad Air 2: Consistent Device Freezing/Reboot with device usage

### ISSUE THREAD

**Issue by jakeajames** [coolstar/electra1131#14]
Device tested: iPad Air 2
Conditions: Jailbroken with latest Electra on iOS 11.3.1. posix_spawn payload enabled, but /usr/lib/TweakInject is emptied. Substitute and TweakInjector are both updated.

Steps to trigger bug (maybe possible to trigger via other methods too, but this is the only one I found that can be done immediately):

1. Open Safari
2. Navigate to https://mobile.twitter.com
3. Login
4. On the homepage start zooming in and out. Zooming amounts must be big and between each zoom-out and zoom-in a short pause of about (less than) a second has to be made.
5. Keep repeating step 4 a few times

Observed behavior: After a few times Safari freezes completely, SpringBoard still works but apps don't launch anymore, they hang as soon as you do it. A few seconds later the whole device is unusable. Assistive Touch is the only thing that works but usually slow and unresponsive. The only possible solutions are:
1. ldrestart (if SSH still happens to work...)
2. Hard reset
3. Wait until it panics

Expected behavior: The Twitter page has a somewhat feature that if the screen resolution changes, it immediately adapts, without having to reload the page. Doing a zoom in or out triggers that mechanism sometimes (if you wait enough after zooming out) and doing it a lot of times overloads memory and causes WebKit to crash. If you do the steps in a non-jailbroken state you'll get notified that WebKit crashed and the page will reload.

By no means this is the only way to trigger it, it has happened me a lot of times randomly, while browsing internet, while watching youtube, while closing apps etc. The freezing has the exact same characteristics, which makes me believe it's all related. The tests were performed by multiple people after I sent instructions and most of them said they got a freeze the first time they tried.

If needed I can provide a video showing how I get it to trigger with no tweaks

**Comment by basilmslmani** [comment]
Got the same result with Iphone 9,3 on 11.1.2 
Only solution is reboot 
This problem wasn’t found before the release of Electra 1131 , maybe the Cydia updates caused it ?

**Comment by coolstar** [comment]
1. Were any stock apps uninstalled?
2. Does this issue still happen if Tweakinject is uninstalled and you run
ldrestart after uninstall TweakInject

**Comment by jakeajames** [comment]
@coolstar Only Tips is but the issue isn't related to tipsd and by looking at other reports the issue isn't related only to WebKit, but also videosubscriptionsd keeps crashing.

The issue happens only with the posix_spawn payload enabled (thus TweakInject is also enabled), somewhat it/they mess up system daemons

I'll try with pspawn_payload and without TweakInject

**Comment by smicelato** [comment]
same prob. first time i get a crash. IpX 11.3.1

**Comment by basilmslmani** [comment]
Stocks app is uninstalled but the issue began after subistitute/tweak injector update that was released with Electra 1131 
Before that my device was running smoothly with 0 issues

**Comment by 123marvin123** [comment]
Got the same crash today for the first time on iPhone 8 on 11.3.1.

**Comment by coolstar** [comment]
Tested here on iPad Pro 10.5". Did the steps listed.

Observed Behavior:
1. Safari hung for 2 seconds
2. SpringBoard restarted (but didn't enter safe mode)
3. Device performs normally after SpringBoard restarting

**Comment by basilmslmani** [comment]
I just wanna mention that this sometimes happen randomly every couple days ( can’t open apps )
1- if I respring it will stuck on the loading screen and will reboot eventually , 
2- ldrestart will restart successfully but the device will be very slow and eventually panics and reboots

**Comment by jakeajames** [comment]
@coolstar for me after Safari hangs & device isn't frozen it just crashes and upon opening it again whole device is frozen. I'm not sure if all devices are affected but a lot of people who tried got the same result with me. The ones who initially didn't, I told them to try again and there it happened.

You could try triggering it again or I could post a video of the freezing in action

**Comment by coolstar** [comment]
Tried repeating the steps again on iPad Pro 10.5" (didn't reboot or anything after it resprung from the prior test)

Safari didn't even hang this time. Device is still responsive and doesn't appear to have any problems.

**Comment by jakeajames** [comment]
@coolstar To get it right you mustn't be very fast (wait about a second so twitter is aware of the zoom) and the zoom must be relatively big. I'd also test on other devices, like your iPhone X

**Comment by basilmslmani** [comment]
@coolstar is there a way to send you a video of the issue ?

**Comment by jakeajames** [comment]
@basilmslmani use the steps I showed and upload it somewhere

**Comment by jakeajames** [comment]
@coolstar here's a video of it in action: 
https://youtu.be/NplD5N1cqeE

**Comment by basilmslmani** [comment]
@coolstar @jakejames 
https://youtu.be/9qCPLX2eOtk
This video shows that random hang issue 
I’ll video your mentioned bug once I get home to my other iPhone

**Comment by nullpixel** [comment]
I can’t reproduce this on my iPhone X, by following the steps. Am I missing something?

**Comment by basilmslmani** [comment]
@nullpixel , @jakejames @coolstar
https://youtu.be/6B-nXQ0W0Lo
Here’s showing what happens

**Comment by jakeajames** [comment]
@nullpixel is the pspawn payload enabled?

**Comment by peterprd** [comment]
I tested it now and I had to hard reset.

iPhone 7 Plus (GSM) 256GB on iOS 11.3.1 with latest Electra MPTCP

**Comment by coolstar** [comment]
get output for following commands: "ps -u root" and "ps -u mobile" when device is in stuck state. Also need output from "socat - UNIX-CONNECT:/var/run/lockdown/syslog.sock" (use watch command). Not possible to debug without that.

**Comment by jakeajames** [comment]
@coolstar can't run ps, SSH disconnects, but here's log https://pastebin.com/zVTfxnPA

**Comment by jakeajames** [comment]
@coolstar got a random freeze, SSH now works https://pastebin.com/raw/WJvb5tv8

**Comment by coolstar** [comment]
Was able to re-produce this issue (finally) on some devices on September 12th

Confirmed fixed in internal build (Electra11.3.1-privbld-09-18-2018)

**Comment by natedog2424** [comment]
How can I get this version of Electra and do I have to completely redo the Jailbreak or can I just re-enable?
