### ISSUE TITLE
Appa keep crashing a couple of times a day

### ISSUE THREAD

**Issue by georgehanna1993** [coolstar/electra1131#8]
Hey Coolstar, i’ve got my 7 plus jailbroken, im on 11.3.1, my iphone keeps crashing all apps a couple of times a day, and i keep re-jailbreaking my iphone almost 3-4 times a day, i downloaded crashreporter, all of the crashes have the same causes, and i dont know how to handle this:

TweakInject.dylib
Libcolorpicker.dylib
Librocketbootstrap.dylib
Libsubstitute.0.dylib

Can u help me ?
Thanks

**Comment by akasarx** [comment]
make sure everythings updated in cydia, make sure EVERY tweak you are using is compatible with the version.
